include:
  - board: seeeduino_xiao_ble
    shield: reno_left
  - board: seeeduino_xiao_ble
    shield: reno_right
  - board: seeeduino_xiao_ble
    shield: reno_dongle
#  - board: seeeduino_xiao_ble
#    shield: settings_reset